require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - bin/**/*
    - vendor/**/*
    - lib/generators/ows/query/*/templates/**/*.rb
